### ISSUE TITLE
Any plans on porting to 1.18.2 and 1.19.x?

### ISSUE THREAD

**Issue by ExDrill** [camcamcamcamcam/momentum#2]
If not, would you mind any contributions? This mod could definitely get a lot more feedback on modern versions, with the new content caves has received! 😄

**Comment by camcamcamcamcam** [comment]
I would like to port but I am quite busy these days so feel free to submit a pull request! I have some plans for changing the mod to work better with Caves and Cliffs but nothing concrete.
